{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block">
    <label>{'Max file size'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int1}&nbsp;MB</p>
</div>
<div class="block">
    <label>{'Max number of files for the upload'|i18n( 'design/standard/class/datatype' )}:</label>
    <p>{$class_attribute.data_int2}</p>
</div>